dataset_root: "./Data"
model_root: "./Models"
dataset: "iWildCam"
num_epochs: 10
batch_size: 16
workers: 8
learning_rate:
  choices: [0.0003,0.0001,0.00003,0.00001]
weight_decay:
  choices: [0,0.000001]
model_name: "Resnet101"
num_epochs_linear: 0
resize: 448
lr_scheduler:
  choices: ["cosine", "step"]
wandb_project_name: "iwc"