dataset_root: $SLURM_TMPDIR/data
model_root: "./Models"
dataset: "iWildCam"
num_epochs: 15
batch_size: 16
workers: 8
learning_rate: 0.00025
weight_decay: 0.0000098
model_name: "Resnet18"
num_epochs_linear: 1
resize: 448
lr_scheduler: "cosine"
wandb_project_name: "iwc"