dataset_root: $SLURM_TMPDIR/data
model_root: "./Models"
dataset: "iWildCam"
num_epochs: 12
batch_size: 16
workers: 8
learning_rate: 0.0001
weight_decay: 0.00001
model_name: "Resnet101"
num_epochs_linear: 0
resize: 448
lr_scheduler: "step"
wandb_project_name: "iwc-820"