dataset_root: "./Data"
model_root: "./Models"
dataset: "iWildCam"
num_epochs: 3
batch_size: 16
workers: 8
learning_rate: 0.0003
weight_decay: 0.00001
model_name: "Resnet18"
num_epochs_linear: 1
resize: 448
lr_scheduler: "cosine"
wandb_project_name: "iwc"