dataset_root: $SLURM_TMPDIR/data
model_root: "./Models"
dataset: "iWildCam"
num_epochs: 40
batch_size: 128
workers: 8
learning_rate: 0.001
weight_decay: 0
model_name: "Resnet18"
num_epochs_linear: 0
resize: 448
lr_scheduler: "NONE"
wandb_project_name: "iwc-patw"